// exports a list of data to use for the example feed
const homeFeed = [
  {
    id: 1,
    parent_id: null,
    user: 'John Doe',
    username: 'JohnDoe@mail.com',
    content: 'Question about our next debriefing at 1200 hours',
    date: 'Wed Oct 18 2017 12:41:34 GMT',
  },
  {
    id: 2,
    parent_id: 1,
    user: 'Jane Smith',
    username: 'JaneSmith@mail.com',
    content: 'Training begins at 0400 hours every Monday',
    date: 'Wed Oct 18 2017 12:41:34 GMT',
  },
  {
    id: 3,
    parent_id: 1,
    user: 'John Doe',
    username: 'JohnDoe@mail.com',
    content: "What's the best army school?",
    date: 'Wed Oct 18 2017 12:41:34 GMT',
  },
  {
    thread_id: 18,
    parent_id: null,
    user: 'Jane Smith',
    username: 'JaneSmith@mail.com',
    content: 'CES is required for all civilian supervisors',
    date: 'Wed Oct 18 2017 12:41:34 GMT',
  },
  {
    id: 5,
    parent_id: 1,
    user: 'John Doe',
    username: 'JohnDoe@mail.com',
    content: 'To build strength I encourage a push/pull split',
    date: 'Wed Oct 18 2017 12:41:34 GMT',
  },
  {
    id: 13,
    parent_id: null,
    user: 'Jane Smith',
    username: 'JaneSmith@mail.com',
    content: 'The Rangers are taking it home this year',
    date: 'Wed Oct 18 2017 12:41:34 GMT',
  },
  {
    id: 831,
    parent_id: 13,
    user: 'John Doe',
    username: 'JohnDoe@mail.com',
    content: 'All personnel debriefing at 1400 hours',
    date: 'Wed Oct 18 2017 12:41:34 GMT',
  },
  {
    id: 389,
    parent_id: 2,
    user: 'John Doe',
    username: 'JohnDoe@mail.com',
    content: 'All personnel debriefing at 1400 hours',
    date: 'Wed Oct 18 2017 12:41:34 GMT',
  },
  {
    id: 3823439,
    parent_id: null,
    user: 'John Doe',
    username: 'JohnDoe@mail.com',
    content: 'TESTINGB',
    date: 'Wed Oct 18 2017 12:41:34 GMT',
  },
];

export default homeFeed;
