# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    volumes:
      - ./seed:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB:  rakkasans

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080