import React from "react";
import { StyleSheet, SafeAreaView, Text } from "react-native";
import { Card, CardItem, Body } from "native-base";
import { ScrollView } from "react-native-gesture-handler";

export default function DivisionHistoryData({}) {
  return (
    <SafeAreaView style={styles.container}>
      <ScrollView>
        <Text style={styles.header}></Text>

        <Card>
          <CardItem>
            <Text>
              NARRATOR: THE 101ST AIRBORNE DIVISION WAS ACTIVATED ON 15 AUGUST
              1942 AT CAMP CLAIBORNE, LOUISIANA. ITS FIRST COMMANDING GENERAL,
              MAJOR GENERAL WILLIAM C. LEE, NOTED THAT THE DIVISION HAD NO
              HISTORY, BUT THAT IT HAD A “RENDEZVOUS WITH DESTINY” AND THAT THE
              NEW DIVISION WOULD BE HABITUALLY CALLED INTO ACTION WHEN THE NEED
              WAS ‘IMMEDIATE AND EXTREME”. THROUGHOUT ITS 70-YEAR HISTORY, THE
              DIVISION HAS AMASSED A PROUD RECORD, IN BOTH WAR AND PEACE,
              UNMATCHED BY ANY OTHER UNIT.
            </Text>
          </CardItem>
        </Card>

        <Card>
          <CardItem>
            <Text>
              FOLLOWING ITS ACTIVATION AND INITIAL TRAINING IN THE UNITED
              STATES, THE DIVISION EMBARKED FOR THE EUROPEAN THEATER OF
              OPERATIONS IN SEPTEMBER, 1943 WHERE IT CONTINUED ITS TRAINING IN
              ENGLAND. DURING THE EARLY MORNING HOURS OF JUNE 6TH, 1944, THE
              SCREAMING EAGLES PARACHUTED INTO THE COAT EN TIN PENINSULA,
              BECOMING THE FIRST ALLIED SOLDIERS TO SET FOOT ONTO OCCUPIED
              FRANCE. THE 101ST AIRBORNE DIVISION, CHARGED WITH CLEARING THE WAY
              FOR THE 4TH INFANTRY DIVISION’S LANDING ON UTAH BEACH, EVENTUALLY
              LINKED THE UTAH AND OMAHA BEACHHEADS AND LIBERATED THE CITY OF
              CARENTAN. AFTER A MONTH OF FIGHTING, THE DIVISION RETURNED TO
              ENGLAND TO PREPARE FOR FUTURE OPERATIONS. ON SEPTEMBER 17TH, 1944
              THE DIVISION JUMPED INTO THE NETHERLANDS SPEARHEADING OPERATION
              MARKET GARDEN. HOLDING A NARROW 16-MILE CORRIDOR THROUGH
              ENEMY-HELD TERRITORY, THE DIVISION FOUGHT AGAINST HEAVY ODDS FOR
              72 DAYS. IN LATE-NOVEMBER, 1944, THE DIVISION RETURNED TO FRANCE
              FOR A WELL-DESERVED REST. THE REST WOULD BE A SHORT ONE. NARRATOR
              QUE: Turn 1.
            </Text>
          </CardItem>
        </Card>

        <Card>
          <CardItem>
            <Text>
              TO COUNTERACT THE MASSIVE GERMAN OFFENSIVE THROUGH THE AR-DENS
              FOREST IN MID-DECEMBER 1944, THE 101ST AIRBORNE DIVISION WAS
              UNEXPECTEDLY RECALLED TO THE FRONT. RESPONSIBLE FOR DEFENDING THE
              CRITICAL ROAD JUNCTION AT BASTOGNE, BELGIUM, THE 101ST AIRBORNE
              DIVISION WAS SURROUNDED BY STRONG ENEMY FORCES THAT DEMANDED ITS
              IMMEDIATE SURRENDER. RESPONDING TO THE GERMAN ULTIMATUM, BRIGADIER
              GENERAL ANTHONY C. MCAULIFFE MADE HISTORY WITH HIS FAMOUS ONE-WORD
              REPLY…”NUTS!”. ALTHOUGH THE SIEGE OF BASTOGNE WAS BROKEN ON
              DECEMBER 26TH, 1944, INTENSE FIGHTING CONTINUED UNTIL MID-JANUARY,
              1945 AS ALLIED UNITS REDUCED NAZI GAINS IN THE AR-DENS SAY-LANT.
              NARRATOR QUE: Turn 2.
            </Text>
          </CardItem>
        </Card>

        <Card>
          <CardItem>
            <Text>
              ATTACKING THE HEART OF GERMANY THROUGH THE RUHR VALLEY, THE 101ST
              AIRBORNE DIVISION PURSUED RETREATING GERMAN FORCES INTO BAVARIA.
              IN SPRING 1945, THE SCREAMING EAGLES LIBERATED THE LANDSBERG
              CONCENTRATION CAMP AND HITLER’S MOUNTAINTOP RETREAT IN
              BERK-TUHS-GOD-EN. THE END OF WORLD WAR II IN EUROPE RELEGATED THE
              101ST AIRBORNE TO OCCUPATION DUTIES IN GERMANY, AUSTRIA, AND
              FRANCE. THE DIVISION WAS INACTIVATED ON NOVEMBER 30TH, 1945.
            </Text>
          </CardItem>
        </Card>

        <Card>
          <CardItem>
            <Text>
              THE IMMEDIATE POST-WAR PERIOD MARKED AN INTERMITTENT EXISTENCE FOR
              THE SCREAMING EAGLES. THE PERIOD IS MARKED BY SEVERAL
              REACTIVATIONS AND INACTIVATIONS AT CAMP BRECKINRIDGE, KENTUCKY AND
              FORT JACKSON, SOUTH CAROLINA. OFFICIAL REACTIVATION CEREMONIES,
              HELD ON SEPTEMBER 21, 1956, MARKED THE 101ST AIRBORNE DIVISION’S
              RETURN TO ACTIVE DUTY AS THE ARMY’S FIRST NUCLEAR CAPABLE,
              PENTOMIC DIVISION AND ITS DEBUT AT FORT CAMPBELL, KENTUCKY. IN
              SEPTEMBER 1956, ELEMENTS OF THE 101ST AIRBORNE DIVISION WERE
              ORDERED TO LITTLE ROCK, ARKANSAS BY PRESIDENT EISENHOWER. AS PART
              OF OPERATION ARKANSAS, THE 1ST AIRBORNE BATTLE GROUP, 327TH
              INFANTRY ESCORTED THE FIRST NINE AFRICA-AMERICAN STUDENTS –THE
              “LITTLE ROCK NINE”— AS THEY ATTENDED CLASSES AT LITTLE ROCK
              CENTRAL HIGH SCHOOL. SUCCESSFUL, THE BASTOGNE BULLDOGS RETURNED TO
              FORT CAMPBELL IN LATE-1956. NARRATOR QUE: Center.
            </Text>
          </CardItem>
        </Card>

        <Card>
          <CardItem>
            <Text>
              ON JULY 29TH, 1965, THE 1ST BRIGADE, 101ST AIRBORNE DIVISION WAS
              ORDERED TO THE REPUBLIC OF VIETNAM EARNING THE NICK-NAME OF “THE
              NOMADS OF VIETNAM”. THE REMAINDER OF THE DIVISION REMAINED AT FORT
              CAMPBELL UNTIL ORDERED TO VIETNAM IN LATE-1967. DURING THE ENEMY’S
              ILL-FATED TET OFFENSIVE IN 1968, THE SCREAMING EAGLES WERE
              INVOLVED IN COMBAT OPERATIONS FROM SAIGON TO QUANG TRI PROVINCE.
            </Text>
          </CardItem>
        </Card>

        <Card>
          <CardItem>
            <Text>
              IN AUGUST 1968, THE SCREAMING EAGLES SHED THEIR PARACHUTES IN
              FAVOR OF HELICOPTER-BORNE OPERATIONS EARNING A NEW
              DESIGNATION---THE 101ST AIRBORNE DIVISION (AIRMOBILE). AFTER THE
              TET OFFENSIVE, THE DIVISION SETTLED INTO THUA THIEN PROVINCE AND
              CONTINUED OFFENSIVE OPERATIONS THERE UNTIL REDEPLOYED TO THE
              UNITED STATES IN EARLY-1972.
            </Text>
          </CardItem>
        </Card>

        <Card>
          <CardItem>
            <Text>
              THE POST VIETNAM PERIOD WAS A TIME OF CHANGE FOR THE ARMY AND THE
              101ST AIRBORNE DIVISION (AIRMOBILE). IN FEBRUARY-1974, THEN-MAJOR
              GENERAL SIDNEY BERRY SIGNED DIVISION GENERAL ORDER 179 AUTHORIZING
              WEAR OF THE NEW AIRMOBILE (LATER AIR ASSAULT) QUALIFICATION BADGE.
              REFLECTING A SHIFT IN STRUCTURE AND ORIENTATION, THE DIVISION WAS
              RE-DESIGNATED AS THE 101ST AIRBORNE DIVISION (AIR ASSAULT) ON
              OCTOBER 4TH, 1974.
            </Text>
          </CardItem>
        </Card>

        <Card>
          <CardItem>
            <Text>
              IN MARCH 1982, ELEMENTS OF THE 101ST AIRBORNE DIVISION (AIR
              ASSAULT) BEGAN SIX-MONTH DEPLOYMENTS TO THE SIANII PENINSULA AS
              MEMBERS OF THE MULTINATIONAL FORCE AND OBSERVERS. TRAGEDY STRUCK
              IN DECEMBER 1985, WHEN 248 SCREAMING EAGLES REDEPLOYING FROM THE
              SIANI WERE KILLED IN A CHARTER AIRPLANE CRASH NEAR GANDER,
              NEWFOUNDLAND.
            </Text>
          </CardItem>
        </Card>

        <Card>
          <CardItem>
            <Text>
              IN AUGUST 1990, THE 101ST AIRBORNE DIVISION (AIR ASSAULT) DEPLOYED
              TO THE MIDDLE EAST IN SUPPORT OF OPERATIONS DESERT SHIELD AND
              DESERT STORM. DURING THE LIBERATION OF KUWAIT, THE DIVISION FIRED
              THE FIRST SHOTS OF THE AIR WAR, AND CONDUCTED THE LONGEST AND
              LARGEST AIR ASSAULT OPERATIONS TO DATE, SECURING IRAQI TERRITORY
              IN THE EUPHRATES RIVER VALLEY. WITH ANNOUNCEMENT OF THE SAFWAN
              CEASE-FIRE IN FEBRUARY, 1991, THE 101ST BEGAN REDEPLOYMENT
              PREPARATIONS. BY MAY 1991, THE SCREAMING EAGLES WERE HOME.
              NARRATOR QUE: Turn 3.
            </Text>
          </CardItem>
        </Card>

        <Card>
          <CardItem>
            <Text>
              THE 1990S WERE A BUSY TIME FOR THE 101ST AIRBORNE DIVISION (AIR
              ASSAULT), SEEING NUMEROUS DEPLOYMENTS IN SUPPORT OF STABILITY AND
              SUPPORT OPERATIONS WORLD-WIDE. FORT CAMPBELL-BASED UNITS WERE
              DEPLOYED TO SOMALIA, HAITI, THE SIANI PENINSULA, CENTRAL AND SOUTH
              AMERICA, BOSNIA, AND KOSOVO.{" "}
            </Text>
          </CardItem>
        </Card>

        <Card>
          <CardItem>
            <Text>
              IN THE WAKE OF THE TERRORIST ATTACKS ON SEPTEMBER 11, 2001,
              ELEMENTS OF THE DIVISION QUICKLY DEPLOYED TO PROTECT SUSCEPTIBLE
              FACILITIES IN THE UNITED STATES FROM POTENTIAL ATTACK. ALMOST
              IMMEDIATELY, THE 3RD BRIGADE COMBAT TEAM DEPLOYED TO AFGHANISTAN
              IN NOVEMBER, 2001. IN MARCH 2002, THE RAKASSANS WERE, IN PART,
              RESPONSIBLE FOR OFFENSIVE OPERATIONS IN THE SHOW-EE-KHOT VALLEY
              THAT DEALT A CRIPPLING EARLY BLOW TO THE TALIBAN AND AL-QAEDA.
              AFTER A CHALLENGING SIX-MONTH DEPLOYMENT, 3RD BRIGADE REDEPLOYED
              TO THE UNITED STATES. NARRATOR QUE: Chinook.
            </Text>
          </CardItem>
        </Card>

        <Card>
          <CardItem>
            <Text>
              IN FEBRUARY AND MARCH 2003, THE DIVISION DEPLOYED TO KUWAIT IN
              ANTICIPATION OF COMBAT OPERATIONS AGAINST SADDAM HUSSEIN’S REGIME
              IN SUPPORT OF OPERATION IRAQI FREEDOM. IN A GRUELING AIR AND
              GROUND MOVEMENT OF 570 KILOMETERS THROUGH HOSTILE TERRITORY AND
              INTENSE COMBAT IN URBAN AREAS, THE DIVISION DISPLAYED ITS
              FLEXIBILITY, LETHALITY, AND FIREPOWER AT EVERY TURN. FIGHTING ITS
              WAY FROM NAJAF, THROUGH KARBALA AND HILLAH, THE DIVISION
              EVENTUALLY CONSOLIDATED IN SOUTHERN BAGHDAD IN MID-APRIL, 2003.
              NARRATOR QUE: Blackhawk .{" "}
            </Text>
          </CardItem>
        </Card>

        <Card>
          <CardItem>
            <Text>
              ORDERED TO NORTHERN IRAQ SHORTLY THEREAFTER, THE DIVISION
              CONDUCTED THE LONGEST AIR ASSAULT IN HISTORY AND QUICKLY ASSUMED
              RESPONSIBILITY FOR MOSUL, IRAQ’S SECOND LARGEST CITY, AND THE FOUR
              SURROUNDING PROVINCES. IN THE MONTHS THAT FOLLOWED, THE DIVISION
              CONCENTRATED ON THE GOALS OF RE-ESTABLISHING SECURITY, THE
              RESTORATION OF BASIC SERVICES, AND RECONSTRUCTION OF CIVILIAN
              INFRASTRUCTURE. DURING THIS PERIOD, THE SCREAMING EAGLES
              UNDERWROTE THE COMPLETION OF 5,000 RECONSTRUCTION PROJECTS, KILLED
              OODAY AND COOSAY HUSSEIN, AND CAPTURED OVER 500 ANTI-COALITION
              INSURGENTS.{" "}
            </Text>
          </CardItem>
        </Card>

        <Card>
          <CardItem>
            <Text>
              THE DIVISION REDEPLOYED TO FORT CAMPBELL IN EARLY-2004. DURING THE
              YEAR THAT FOLLOWED, THE 101ST AIRBORNE DIVISION (AIR ASSAULT)
              FULLY RECOVERED AND COMPLETELY REORGANIZED UNDER THE NEW ARMY
              TRANSFORMATION ORGANIZATIONAL STRUCTURE IN ANTICIPATION OF ITS
              SECOND DEPLOYMENT TO IRAQ.
            </Text>
          </CardItem>
        </Card>

        <Card>
          <CardItem>
            <Text>
              IN NOVEMBER 2005, THE DIVISION HEADQUARTERS, THE 1ST AND 3RD
              BRIGADE COMBAT TEAMS, AND THE 101ST COMBAT AVIATION BRIGADE
              DEPLOYED TO IRAQ FOR A SECOND TIME. AS TASK FORCE BAND OF
              BROTHERS, THE DIVISION ASSUMED RESPONSIBILITY FOR THE NORTHERN
              HALF OF IRAQ; THE LARGEST AREA OF OPERATION IN THE COUNTRY.{" "}
            </Text>
          </CardItem>
        </Card>

        <Card>
          <CardItem>
            <Text>
              PARTNERED WITH FOUR IRAQI ARMY DIVISIONS, THE SCREAMING EAGLES
              FOCUSED THEIR EFFORTS ON DEVELOPING CREDIBLE IRAQI SECURITY FORCE
              UNITS THAT WERE CAPABLE OF INDEPENDENT COUNTER-INSURGENCY
              OPERATIONS. NARRATOR QUE: Center.
            </Text>
          </CardItem>
        </Card>

        <Card>
          <CardItem>
            <Text>
              THIS MONUMENTAL EFFORT RESULTED IN VASTLY IMPROVED SECURITY AND
              THE TRANSFER OF SEVERAL AREAS TO IRAQI CONTROL PRIOR TO THE
              DIVISION’S REDEPLOYMENT IN OCTOBER, 2006. UNDER THE NEW MODULAR
              STRUCTURE, 2ND AND 4TH BRIGADE COMBAT TEAMS AND THE 159TH COMBAT
              AVIATION BRIGADE WERE ATTACHED TO OTHER MULTINATIONAL DIVISION OR
              MULTINATIONAL FORCE COMMANDS ELSEWHERE IN IRAQ.
            </Text>
          </CardItem>
        </Card>

        <Card>
          <CardItem>
            <Text>
              FORT CAMPBELL ENTERED THE FINAL PHASES OF THE ARMY’S HISTORIC
              MODULAR TRANSFORMATION IN LATE 2006. IN THIS PHASE, THE EIGHTEENTH
              AIRBORNE CORPS SHED ITS PEACETIME COMMAND RESPONSIBILITIES FOR THE
              101ST AIRBORNE DIVISION (AIR ASSALT) – A RELATIONSHIP THAT BEGAN
              PRIOR TO THE 1944 INVASION OF HOLLAND, AND THE DIVISION BECAME A
              DIRECT REPORTING UNIT TO FORCES COMMAND. ADDITIONAL COMMAND AND
              CONTROL CHANGES SAW FORT LEE, VIRGINIA’S 49TH QUARTERMASTER GROUP
              JOIN THE FORT CAMPBELL FAMILY.
            </Text>
          </CardItem>
        </Card>

        <Card>
          <CardItem>
            <Text>
              LATE-2007 SAW THE MAJORITY OF THE DIVISION DEPLOYED AGAIN. THE
              DIVISION’S 1ST, 2ND, AND 3RD BRIGADE COMBAT TEAMS AND ELEMENTS OF
              THE SUSTAINMENT BRIGADE DEPLOYED INDEPENDENTLY TO IRAQ WHERE EACH
              SERVED UNDER THE COMMAND OF DIFFERENT MULTINATIONAL DIVISIONS THEN
              CONDUCTING COMBAT OPERATIONS THROUGHOUT IRAQ. SOLDIERS OF THE 49TH
              QUARTERMASTER DEPLOYED TO BOTH IRAQ AND AFGHANISTAN TO SUPPORT
              COMBAT AND COMBAT SUPPORT OPERATIONS. THE 101ST COMBAT AVIATION
              BRIGADE DEPLOYED TO AFGHANISTAN AND WAS EVENTUALLY RELIEVED BY THE
              159TH COMBAT AVIATION BRIGADE.
            </Text>
          </CardItem>
        </Card>

        <Card>
          <CardItem>
            <Text>
              IN MARCH 2008, THE HEADQUARTERS (AND SPECIAL TROOPS BATTALION)
              101ST AIRBORNE DIVISION (AIR ASSAULT) JOINED THE 4TH BRIGADE
              COMBAT TEAM AND THE 101ST SUSTAINMENT BRIGADE IN AFGHANISTAN IN
              SUPPORT OF OPERATION ENDURING FREEDOM. AS COMBINED JOINT TASK
              FORCE 101, THE DIVISION HEADQUARTERS WAS SUPPORTED BY MANY
              ATTACHED COALITION UNITS AND WAS RESPONSIBLE FOR AN AREA OF
              OPERATION THE SIZE OF PENNSYLVANIA, DESIGNATED AS REGIONAL
              COMMAND-EAST.{" "}
            </Text>
          </CardItem>
        </Card>

        <Card>
          <CardItem>
            <Text>
              COMPOSED OF 14 PROVINCES, INCLUDING MUCH OF THE VOLATILE BORDER
              REGION BETWEEN AFGHANISTAN AND PAKISTAN, AS WELL AS THE HINDU KUSH
              AND AFGHAN CONTROL HIGHLANDS, REGIONAL COMMAND-EAST POSED AN
              UNIQUE AND DIFFICULT SET OF CHALLENGES UNLIKE ANYTHING PREVIOUSLY
              EXPERIENCED.{" "}
            </Text>
          </CardItem>
        </Card>

        <Card>
          <CardItem>
            <Text>
              THE SOLDIERS OF COMBINED JOINT TASK FORCE-101 THRIVED IN THEIR
              ROLE AS BOTH SOLDIER/DIPLOMATS AND WARRIORS. COMBINED JOINT TASK
              FORCE - 101 HELPED RESTORE THE AFGHAN PEOPLE’S CONFIDENCE AND
              TRUST IN THEIR GOVERNMENT, WHILE IMPROVING THEIR QUALITY OF LIFE
              THROUGH MORE THAN 2500 INNOVATIVE DEVELOPMENT PROJECTS. AS
              WARRIORS, COMBINED JOINT TASK FORCE - 101 AGGRESSIVELY TRAINED
              AFGHAN NATIONAL SECURITY FORCES (ANSF) AND, SIDE-BY-SIDE,
              RELENTLESSLY PURSUED INSURGENT GROUPS WHEREVER THEY COULD BE
              FOUND.{" "}
            </Text>
          </CardItem>
        </Card>

        <Card>
          <CardItem>
            <Text>
              THROUGHOUT 2010, 1ST, 2ND, 3RD, 4TH BRIGADE COMBAT TEAMS, 101ST
              SUSTAINMENT BRIGADE, 159TH AND 101ST COMBAT AVIATION BRIGADE
              DEPLOYED TO AFGHANISTAN AT DIFFERENT TIMES THROUGHOUT THE YEAR.
              THE 101ST DIVISION HEADQUARTERS COMMANDS RC-EAST FOR THE SECOND
              TIME AS THE ENTIRE DIVISION IS DEPLOYED IN THE SAME THEATER OF
              OPERATIONS.
            </Text>
          </CardItem>
        </Card>

        <Card>
          <CardItem>
            <Text>
              ON MAY 2, 2011, SPECIAL FORCES SOLDIERS AND NAVY SEALS KILLED
              OSAMA BIN LADEN, FOUNDER OF AL-QAEDA AND RESPONSIBLE FOR THE 9/11
              ATTACKS. SHORTLY AFTER BIN LADEN'S DEATH, PRESIDENT BARACK OBAMA
              VISITED FORT CAMPBELL TO THANK 160TH SPECIAL OPERATIONS AVIATION
              REGIMENT SOLDIERS AND SOLDIERS IN THE DIVISION. DURING THE SUMMER
              AND FALL OF 2012, ELEMENTS OF THE 1ST, 2ND, AND 3RD BRIGADE COMBAT
              TEAMS, AS WELL AS THE 101ST COMBAT AVIATION BRIGADE, AGAIN
              DEPLOYED TO AFGHANISTAN.{" "}
            </Text>
          </CardItem>
        </Card>

        <Card>
          <CardItem>
            <Text>
              IN EARLY 2013, THE 101ST DIVISION HEADQUARTERS, 101ST SUSTAINMENT
              BRIGADE, AND 4TH BRIGADE COMBAT TEAM DEPLOYED TO AFGHANISTAN. THE
              101ST DIVISION HEADQUARTERS COMMANDS RC-EAST FOR THE THIRD TIME IN
              FIVE YEARS.
            </Text>
          </CardItem>
        </Card>

        <Card>
          <CardItem>
            <Text>
              LATER IN 2013, ELEMENTS OF THE 1ST, 2ND, 3RD, AND 4TH BRIGADE
              COMBAT TEAM, AND THE 101ST CAB, RETURN HOME TO FORT CAMPBELL.{" "}
            </Text>
          </CardItem>
        </Card>

        <Card>
          <CardItem>
            <Text>
              IN EARLY 2014, THE 101ST DIVISION HEADQUARTERS, 101ST SUSTAINMENT
              BRIGADE, AND THE REMAINING ELEMENTS OF 4TH BRIGADE COMBAT TEAM
              RETURN HOME FROM DEPLOYMENT TO AFGHANISTAN WHILE ELEMENTS OF 2ND
              BRIGADE COMBAT TEAM AND 159TH COMBAT AVIATION BRIGADE DEPLOYED TO
              AFGHANISTAN.
            </Text>
          </CardItem>
        </Card>

        <Card>
          <CardItem>
            <Text>
              THE DIVISION'S EFFORTS IN AFGHANISTAN RESULTED IN SUCCESSFUL AND
              DECISIVE OPERATIONS AT EVERY LEVEL PRODUCING A SIGNIFICANTLY
              IMPROVED AFGHAN NATIONAL SECURITY FORCE COMMITTED TO THE DEFENSE
              OF THEIR COUNTRY. SIMILARLY, SCREAMING EAGLES IN IRAQ MEASURABLY
              IMPROVED THE QUALITY OF LIFE OF THE IRAQI PEOPLE AND THEIR TRUST
              IN THE IRAQI ARMY.
            </Text>
          </CardItem>
        </Card>

        <Card>
          <CardItem>
            <Text>
              IN LATE 2014, THE DIVISION HEADQUARTERS AND ELEMENTS OF THE 101ST
              SUSTAINMENT BRIGADE DEPLOYED IN SUPPORT OF OPERATION UNITED
              ASSISTANCE, THE MISSION TO ERADICATE EBOLA IN LIBERIA. THE
              DIVISION’S EFFORTS GREATLY ASSISTED IN THE CONTAINMENT OF THE
              VIRUS. AS OF MAY 15, THERE WERE ZERO REPORTED NEW CASES OF EBOLA
              IN LIBERIA.
            </Text>
          </CardItem>
        </Card>

        <Card>
          <CardItem>
            <Text>
              IN EARLY 2016, THE DIVISION HEADQUARTERS DEPLOYED TO IRAQ AS THE
              COMMAND ELEMENT OF THE COMBINED JOINT FORCES LAND COMPONENT
              COMMAND IN SUPPORT OF OPERATION INHERENT RESOLVE. THE HEADQUARTERS
              WORKED IN CONJUNCTION WITH 19 COALITION NATIONS TO ENABLE THE
              IRAQI SECURITY FORCES TO DRIVE DAESH FROM IRAQ. 2ND BRIGADE COMBAT
              TEAM FOLLOWED THE HEADQUARTERS INTO THEATRE IN SPRING 2016 AND WAS
              ESSENTIAL IN ADVISE AND ASSIST OPERATIONS THAT HELPED BRING ABOUT
              THE DEFEAT OF DAESH.
            </Text>
          </CardItem>
        </Card>

        <Card>
          <CardItem>
            <Text>
              IN LATE 2016, THE DIVISION HEADQUARTERS RETURNED TO FORT CAMPBELL.
            </Text>
          </CardItem>
        </Card>

        <Card>
          <CardItem>
            <Text>
              IN EARLY 2018, THE DIVISION HEADQUARTERS DEPLOYED TO AFPHANISTAN
              WHERE, JOINED BY ELEMENTS OF DIVARTY THE KENTUCKY MCP-OD, IT
              SERVED IN SUPPORT OF OPERATION RESOLUTE SUPPORT. THE SCREAMING
              EAGLES WERE CHARGED WITH OVERSEEING NATO’S TRAIN, ADVISE, AND
              ASSIST MISSION AND U.S. COUNTER-TERRORISM OPERATIONS. THEY
              RETURNED IN LATE 2018.
            </Text>
          </CardItem>
        </Card>

        <Card>
          <CardItem>
            <Text>
              AS WE LOOK TO THE FUTURE, ONE THING REMAINS CERTAIN TODAY AS IT
              DID IN TIMES PAST - “WHEN THE ARMY WANTS IT DONE THEY WILL CALL
              THE 1-0-1". THIS DIVISIONS TIME HONORED TRADITION OF ANSWERING THE
              NATIONS CALL WILL ENDURE AS WE CONTINUE TO PRODUCE THE BEST
              TRAINED, MOST HIGHLY DISCIPLINED, AGILE AND ADAPTABLE UNITS THAT
              DELIVER AN UNMATCHED FORCIBLE ENTRY AIR ASSAULT CAPABILITY,
              PREPARED TO FIGHT AND WIN DECISIVELY WHEREVER AND WHENEVER WE ARE
              CALLED.
            </Text>
          </CardItem>
        </Card>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  main: {
    marginBottom: 200,
  },
  container: {
    width: "100%",
    height: "100%",
    flexDirection: "column",
    paddingHorizontal: 15,
    paddingVertical: 10,
  },
  title: {
    fontSize: 15,
    fontWeight: "500",
  },
  header: {
    fontSize: 20,
    fontWeight: "700",
    marginTop: 20,
    marginBottom: 20,
    textAlign: "center",
  },
});


